/**
 * Saves the full list of 116 reels scraped from @deborakaillany profile.
 * Ordered oldest to newest (2020 → 2026).
 * Run once: pnpm tsx scripts/shorts-automation/scrape-and-save.ts
 */

import { writeFile, mkdir } from "fs/promises";
import { join } from "path";

const DATA_DIR = join(__dirname, "../../data");

// All 116 reel shortcodes from @deborakaillany (oldest → newest)
const ALL_REEL_IDS = [
  "B_LrQHunrj7", "ChxW63Ajox8", "CvDIfyqt9IP", "CwbYdrJNcSB",
  "DFtJbFePEEI", "DFvNqwqOfrA", "DFvuc9dvvyY", "DF6DJ_wv7EO",
  "DF8oKAiPnCV", "DF_LDIjvt6z", "DG30hDfPJT0", "DG6ZSghPbcP",
  "DHHSONQPTx0", "DH0-OO8RFq0", "DH6wo4NPKHL", "DICfkVRPV2o",
  "DIcPbjcP7kl", "DIe0CGOTwiG", "DIj92W-PIKq", "DImiThUvsD4",
  "DIpPNlrv72a", "DIzalp9vus8", "DI4kqFYJW6m", "DJASo-WPQ3j",
  "DJC3ZaTvxid", "DJFcaQFP_Nk", "DJSUNukvhHO", "DJU4zc6PvrR",
  "DJXeZJ-PHU_", "DJaCimmvEi2", "DJcnWNsvVvz", "DJkVttGPoRm",
  "DJm6hf-PDfI", "DJpfF_IPkuk", "DJsDXZkvac6", "DJuo5yBvk2r",
  "DJ2XPXnPfUb", "DJ48KEDvQ54", "DJ7hROMPO42", "DJ-Fu8lPqto",
  "DKAq3FrPkCI", "DKIY1L-vzB2", "DKK9xodv8J7", "DKNidgCvjrS",
  "DKQHQK9vc5L", "DKSsOlTv-d_", "DKaahPLvFri", "DKc_CsivWR4",
  "DKfkAMqvdtT", "DKiI0AfPc77", "DKkt6dXvWqo", "DKsb9JJvjBS",
  "DKvAkq4v9Mw", "DKw9SEAxabY", "DKxlt_0PXWJ", "DK2vBBTPTSH",
  "DK-eGYUvlRz", "DLBB16wvo1X", "DLDnA27Pk5f", "DLGL8tDvef4",
  "DLIww2ovQUM", "DLSfCUIM2F9", "DLTD82DPpTP", "DLYOINzvMQq",
  "DLayksGP8FA", "DLiff7cvlk0", "DLlFVRpvGAD", "DLs0CL8v3xK",
  "DL0iUJ4vj4d", "DL5rxXbvRhY", "DL8Qv_xvj9j", "DL-1VTTPyuh",
  "DMJIiR9vmSK", "DMQ2lsePpRr", "DMYlQtav1Tp", "DMtLyiJPe69",
  "DM8oiYjPERb", "DM_M5VkPxnl", "DNBxTCGP7JP", "DNytIbwXJoF",
  "DN9AYqzDk9S", "DO6z9vujln2", "DPtjn5QDZHD", "DPxcXk4jIE5",
  "DQH8g3ZEX6H", "DQIDWBIDnlc", "DQNMwaHDmKw", "DQnI_eODnbt",
  "DQsGg5WDm-i", "DSlH1SADsy_", "DS3JdpADpIk", "DS5uM7hDhEo",
  "DTBcrGsDpgA", "DTQ5sv2jrIz", "DTgYLtODsiV", "DTtOFkQjhLh",
  "DTvy7isjn8D", "DT08lJZjnIx", "DT3hP3OjmZV", "DT_PzZBDvDv",
  "DUB0R8qDr_K", "DU6eCEoDhnN", "DU9Cy2_Dgbw", "DVJ6N75DlT1",
  "DVMfnydjoRh", "DVPEXjSDjWA", "DVZXhMMjkRI", "DVb8c7lDhJM",
  "DVrZIcxDjaS", "DV1sTT8DqDt", "DV9ajXJuAfs", "DV__XUouXdL",
  "DWhd0HJu81N", "DWmnf2DOSif", "DWpMDoUOes8", "DIhZB1Tzno_",
];

async function main() {
  await mkdir(DATA_DIR, { recursive: true });

  const reels = ALL_REEL_IDS.map((id) => ({
    id,
    caption: "", // Will be generated by AI
    permalink: `https://www.instagram.com/reel/${id}/`,
  }));

  await writeFile(
    join(DATA_DIR, "reels-list.json"),
    JSON.stringify(reels, null, 2),
  );

  console.log(`Saved ${reels.length} reels to data/reels-list.json`);
}

main();
